#!/usr/bin/env python3
"""
build-data.py — Merges all data sources into ops-dashboard/load-data.js
Run after any data update (Qlik fetch, shift history append, manual score entry).

Usage:
  python ops-dashboard/build-data.py
"""
import json
import os
from datetime import datetime, timezone

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, "data")


def load_json(filename, default):
    path = os.path.join(DATA, filename)
    if not os.path.exists(path):
        return default
    with open(path) as f:
        return json.load(f)


def main():
    team_config       = load_json("team_config.json",       {"reps": []})
    sampling_scores   = load_json("sampling_scores.json",   [])
    qlik_daily        = load_json("qlik_daily.json",        [])
    qlik_team_daily   = load_json("qlik_team_daily.json",   [])
    shift_history     = load_json("shift_history.json",     [])
    shift_schedule    = load_json("shift_schedule.json",    [])
    rotem_comments    = load_json("rotem_comments.json",    [])

    data = {
        "generated_at":    datetime.now(timezone.utc).isoformat(),
        "team_config":     team_config,
        "sampling_scores": sampling_scores,
        "qlik_daily":      qlik_daily,
        "qlik_team_daily": qlik_team_daily,
        "shift_history":   shift_history,
        "shift_schedule":  shift_schedule,
        "rotem_comments":  rotem_comments,
    }

    out_path = os.path.join(BASE, "load-data.js")
    with open(out_path, "w") as f:
        f.write("// Auto-generated by build-data.py — do not edit manually\n")
        f.write("window.OPS_DATA = ")
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    print(f"[build-data] Written {out_path}")
    print(f"  sampling_scores:  {len(sampling_scores)} records")
    print(f"  rotem_comments:   {len(rotem_comments)} comments")
    print(f"  qlik_team_daily:  {len(qlik_team_daily)} days")
    print(f"  shift_schedule:   {len(shift_schedule)} shifts")
    print(f"  shift_history:    {len(shift_history)} records")
    print(f"  generated_at:     {data['generated_at']}")


if __name__ == "__main__":
    main()
